
import React, { useState } from 'react';
import { analyzeMedia } from '../services/geminiService';

const ImageAnalyzer: React.FC = () => {
  const [analysis, setAnalysis] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [mediaType, setMediaType] = useState<'image' | 'video'>('image');

  const handleFile = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    setLoading(true);
    setAnalysis(null);
    const isVideo = file.type.startsWith('video/');
    setMediaType(isVideo ? 'video' : 'image');

    const reader = new FileReader();
    reader.onload = async () => {
      const base64 = (reader.result as string).split(',')[1];
      const result = await analyzeMedia(base64, file.type, isVideo);
      setAnalysis(result);
      setLoading(false);
    };
    reader.readAsDataURL(file);
  };

  return (
    <div className="bg-white p-8 rounded-[40px] border border-slate-100 shadow-sm">
      <div className="flex justify-between items-start mb-4">
        <h3 className="text-2xl font-black text-[#002B5B]">Media Intelligence</h3>
        <span className="text-[10px] font-black uppercase bg-blue-50 text-blue-600 px-3 py-1 rounded-full border border-blue-100">Gemini 3 Pro</span>
      </div>
      <p className="text-slate-500 text-sm mb-6 font-medium">Upload a photo or video of any vehicle to get instant AI evaluation and key insights.</p>
      
      {!analysis && !loading ? (
        <div className="space-y-4">
          <label className="flex flex-col items-center justify-center w-full h-48 border-2 border-dashed border-slate-200 rounded-[32px] cursor-pointer hover:bg-slate-50 hover:border-blue-300 transition-all group">
            <div className="flex flex-col items-center justify-center pt-5 pb-6">
              <div className="w-12 h-12 bg-blue-50 text-blue-500 rounded-2xl flex items-center justify-center mb-4 group-hover:scale-110 transition">
                <svg className="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 16a4 4 0 01-.88-7.903A5 5 0 1115.9 6L16 6a5 5 0 011 9.9M15 13l-3-3m0 0l-3 3m3-3v12"/></svg>
              </div>
              <p className="text-[10px] font-black text-slate-500 uppercase tracking-widest">Select Image or Video</p>
              <p className="text-[9px] text-slate-400 mt-1">MP4, JPG, PNG supported</p>
            </div>
            <input type="file" className="hidden" accept="image/*,video/*" onChange={handleFile} />
          </label>
        </div>
      ) : loading ? (
        <div className="h-48 flex flex-col items-center justify-center animate-pulse">
          <div className="w-8 h-8 border-3 border-blue-600 border-t-transparent rounded-full animate-spin mb-4"></div>
          <p className="text-blue-600 font-black uppercase text-[10px] tracking-widest">Analyzing Media Context...</p>
        </div>
      ) : (
        <div className="bg-slate-50 p-6 rounded-[32px] border border-slate-100 animate-in fade-in zoom-in duration-300">
          <div className="flex items-center space-x-2 mb-4">
            <span className="text-lg">{mediaType === 'video' ? '🎬' : '📸'}</span>
            <h4 className="text-sm font-black text-[#002B5B] uppercase tracking-wider">AI Report</h4>
          </div>
          <div className="max-h-64 overflow-y-auto pr-2 custom-scrollbar">
            <p className="text-sm text-slate-700 whitespace-pre-wrap leading-relaxed font-medium">{analysis}</p>
          </div>
          <div className="mt-6 pt-6 border-t border-slate-200 flex justify-between items-center">
            <button onClick={() => setAnalysis(null)} className="text-[10px] font-black uppercase text-blue-600 hover:text-blue-700 transition flex items-center">
              <svg className="w-3 h-3 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/></svg>
              New Analysis
            </button>
            <span className="text-[9px] font-bold text-slate-400">REPORT GENERATED BY GEMINI PRO</span>
          </div>
        </div>
      )}
    </div>
  );
};

export default ImageAnalyzer;
